### ISSUE TITLE
bs4.FeatureNotFound

### ISSUE THREAD

**Issue by dev-shah-2204** [ReaperZ0v/csgo-stats-scraper#1]
After installing all the requirements, when I run the file, it gives an error.
```
Traceback (most recent call last):
  File "path/csgo_scraper.py", line 37, in <module>
    csgo_scrape(10)
  File "path/csgo_scraper.py", line 14, in csgo_scrape
    soup_object = BeautifulSoup(site_resp, "lxml")
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\bs4\__init__.py", line 243, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

Could you tell me how I am supposed to run this?

**Comment by ReaperZ0v** [comment]
run command :

```pip3 install lxml```
this is the parser library needed

**Comment by ReaperZ0v** [comment]
run command :

```pip3 install lxml```
this is the parser library needed
